name: webrtc_calling
description: A reusable Flutter package for WebRTC calling features including Keypad, Call UI, and Service management.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  sip_ua:
    git:
      url: https://github.com/cloudwebrtc/dart-sip-ua.git
  flutter_callkit_incoming: ^3.0.0
  uuid: ^4.5.2
  flutter_webrtc: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
